-- MySQL Script generated by MySQL Workbench
-- Tue May 11 17:56:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDlol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDlol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDlol` DEFAULT CHARACTER SET utf8 ;
USE `BDlol` ;

-- -----------------------------------------------------
-- Table `BDlol`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`jogador` (
  `idJogador` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `idade` INT NULL,
  `EA` INT NULL,
  `EL` INT NULL,
  `gemas` INT NULL,
  `baus` INT NULL,
  `chaves` INT NULL,
  PRIMARY KEY (`idJogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`campeao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`campeao` (
  `idCampeao` INT NOT NULL AUTO_INCREMENT,
  `nomeCampeao` VARCHAR(45) NOT NULL,
  `textoCampeao` VARCHAR(45) NULL,
  `regiao` VARCHAR(45) NULL,
  `precoCampeao` INT NULL,
  `imagemCampeao` LONGBLOB NULL,
  PRIMARY KEY (`idCampeao`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `BDlol`.`feiticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`feiticos` (
  `idFeiticos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `texto` TINYTEXT NULL,
  `imagemFeitico` LONGBLOB NULL,
  PRIMARY KEY (`idFeiticos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`itens` (
  `idItens` INT NOT NULL AUTO_INCREMENT,
  `nomeItem` VARCHAR(45) NULL,
  `textoItem` TINYTEXT NULL,
  `precoItem` INT NULL,
  `imagemItem` LONGBLOB NULL,
  PRIMARY KEY (`idItens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`skins` (
  `idSkin` INT NOT NULL AUTO_INCREMENT,
  `nomeSkin` VARCHAR(45) NULL,
  `campeao_id` INT NOT NULL,
  `precoSkin` INT NULL,
  `imagemSkin` LONGBLOB NULL,
  PRIMARY KEY (`idSkin`),
  INDEX `fk_skins_campeao1_idx` (`campeao_id` ASC),
  CONSTRAINT `fk_skins_campeao1`
    FOREIGN KEY (`campeao_id`)
    REFERENCES `BDlol`.`campeao` (`idCampeao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`maestria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`maestria` (
  `pontos` FLOAT NULL,
  `nivel` INT NULL,
  `jogador_id` INT NOT NULL,
  `campeao_id` INT NOT NULL,
  INDEX `fk_maestria_jogador1_idx` (`jogador_id` ASC),
  INDEX `fk_maestria_campeao1_idx` (`campeao_id` ASC),
  PRIMARY KEY (`jogador_id`, `campeao_id`),
  CONSTRAINT `fk_maestria_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `BDlol`.`jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maestria_campeao1`
    FOREIGN KEY (`campeao_id`)
    REFERENCES `BDlol`.`campeao` (`idCampeao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`partida` (
  `idPartida` INT NOT NULL AUTO_INCREMENT,
  `duracao` TIME NULL,
  PRIMARY KEY (`idPartida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`jogador_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`jogador_partida` (
  `idJP` INT NOT NULL AUTO_INCREMENT,
  `ouro` INT NULL,
  `danoCampeoes` INT NULL,
  `danoRecebido` INT NULL,
  `tropasAbatidas` INT NULL,
  `placarVisao` INT NULL,
  `jogador_id` INT NOT NULL,
  `partida_idPartida` INT NOT NULL,
  `skins_idSkin` INT NULL,
  `campeao_idCampeao` INT NOT NULL,
  `lado` ENUM('A', 'V') NOT NULL,
  `resultado` ENUM('V', 'D') NOT NULL,
  INDEX `fk_jogador_partida_jogador1_idx` (`jogador_id` ASC),
  INDEX `fk_jogador_partida_partida1_idx` (`partida_idPartida` ASC),
  INDEX `fk_jogador_partida_skins1_idx` (`skins_idSkin` ASC),
  PRIMARY KEY (`idJP`),
  INDEX `fk_jogador_partida_campeao1_idx` (`campeao_idCampeao` ASC),
  CONSTRAINT `fk_jogador_partida_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `BDlol`.`jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_partida_partida1`
    FOREIGN KEY (`partida_idPartida`)
    REFERENCES `BDlol`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_partida_skins1`
    FOREIGN KEY (`skins_idSkin`)
    REFERENCES `BDlol`.`skins` (`idSkin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_partida_campeao1`
    FOREIGN KEY (`campeao_idCampeao`)
    REFERENCES `BDlol`.`campeao` (`idCampeao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`itens_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`itens_partida` (
  `idIP` INT NOT NULL AUTO_INCREMENT,
  `jogador_partida_idJP` INT NOT NULL,
  `partida_idPartida` INT NOT NULL,
  `itens_idItens` INT NULL,
  INDEX `fk_itens_partida_jogador_partida1_idx` (`jogador_partida_idJP` ASC),
  INDEX `fk_itens_partida_partida1_idx` (`partida_idPartida` ASC),
  INDEX `fk_itens_partida_itens1_idx` (`itens_idItens` ASC),
  PRIMARY KEY (`idIP`),
  CONSTRAINT `fk_itens_partida_jogador_partida1`
    FOREIGN KEY (`jogador_partida_idJP`)
    REFERENCES `BDlol`.`jogador_partida` (`idJP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_partida_partida1`
    FOREIGN KEY (`partida_idPartida`)
    REFERENCES `BDlol`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_partida_itens1`
    FOREIGN KEY (`itens_idItens`)
    REFERENCES `BDlol`.`itens` (`idItens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`feiticos_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`feiticos_partida` (
  `idFP` INT NOT NULL AUTO_INCREMENT,
  `jogador_partida_idJP` INT NOT NULL,
  `feiticos_id` INT NOT NULL,
  `partida_idPartida` INT NOT NULL,
  INDEX `fk_feiticos_partida_jogador_partida1_idx` (`jogador_partida_idJP` ASC),
  INDEX `fk_feiticos_partida_feiticos1_idx` (`feiticos_id` ASC),
  INDEX `fk_feiticos_partida_partida1_idx` (`partida_idPartida` ASC),
  PRIMARY KEY (`idFP`),
  CONSTRAINT `fk_feiticos_partida_jogador_partida1`
    FOREIGN KEY (`jogador_partida_idJP`)
    REFERENCES `BDlol`.`jogador_partida` (`idJP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feiticos_partida_feiticos1`
    FOREIGN KEY (`feiticos_id`)
    REFERENCES `BDlol`.`feiticos` (`idFeiticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feiticos_partida_partida1`
    FOREIGN KEY (`partida_idPartida`)
    REFERENCES `BDlol`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDlol`.`skins_jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDlol`.`skins_jogador` (
  `jogador_id` INT NOT NULL,
  `skins_idSkin` INT NOT NULL,
  INDEX `fk_skins_jogador_jogador1_idx` (`jogador_id` ASC),
  INDEX `fk_skins_jogador_skins1_idx` (`skins_idSkin` ASC),
  PRIMARY KEY (`jogador_id`, `skins_idSkin`),
  CONSTRAINT `fk_skins_jogador_jogador1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `BDlol`.`jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skins_jogador_skins1`
    FOREIGN KEY (`skins_idSkin`)
    REFERENCES `BDlol`.`skins` (`idSkin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- VIEW
-- -----------------------------------------------------
create view vw_partida_completa as select idPartida, duracao, ouro, danoCampeoes, danoRecebido, tropasAbatidas, placarVisao, lado, resultado, nickname, nomeCampeao, nomeSkin
FROM jogador_partida
LEFT JOIN skins
ON idSkin=skins_idSkin
INNER JOIN jogador
ON jogador.idJogador=jogador_partida.jogador_id
INNER JOIN campeao
ON idCampeao=jogador_partida.campeao_idCampeao
INNER JOIN partida
ON idPartida=partida_idPartida;


-- -----------------------------------------------------
-- PROCEDURE
-- -----------------------------------------------------
delimiter $$
create procedure pr_mostra_skins (nick varchar(45))
begin
	select idSkin, nomeSkin, imagemSkin, nomeCampeao from jogador
	join skins_jogador sj on idJogador = sj.jogador_id
	join skins s on skins_idSkin = idSkin
	join campeao on s.campeao_id = idCampeao
	join maestria m on idJogador = m.jogador_id and idCampeao = m.campeao_id
    where nickname = nick;
end $$
delimiter ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
